[mqtt]
broker = "10.8.254.1:1883"
item_base = "catt/items"
client-id = "catt-zwave"

[zwave]
port = "/dev/ttyUSB0"
expose_unbound = true
sys_config = "/etc/openzwave-git"
user_config = "./config"

[[zwave.device]]
id = 1
name = "controller"

[[zwave.device]]
id = 2
name = "Light_Living_Table"
zwave_label = "level"
value_type = "int"
